name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Add step to regenerate the configure script if it doesn't exist
    - name: Regenerate configure script
      run: |
        if [ ! -f ./configure ]; then
          autoreconf --install
        fi

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
